(() => {
  const figure = (src, alt, caption) => `<figure class="figure-box"><img src="${src}" alt="${alt}"><figcaption>${caption}</figcaption></figure>`;
  const mcq = (id, level, module, topic, source, prompt, options, answer, explanation, image = '') => ({ id, level, module, type:'mcq', topic, source, prompt, options, answer, explanation, figure:image });
  const short = (id, level, module, topic, source, prompt, answers, displayAnswer, explanation, image = '') => ({ id, level, module, type:'short', topic, source, prompt, answers, displayAnswer, explanation, figure:image });
  const gramProcess = figure('assets/lessons-03-06/gram-stain-process.jpg', 'A four-step Gram-staining chart showing crystal violet, iodine, alcohol decolorization, and safranin effects on Gram-positive and Gram-negative cells.', 'Gram-stain process supplied with Lesson 05');
  const endosporeProcess = figure('assets/lessons-03-06/endospore-process.jpg', 'A chart showing endospore-forming and non-endospore-forming rods after heat, malachite green, water, and safranin.', 'Endospore-stain process supplied with Lesson 06');
  const acidFastSlide = figure('assets/lessons-03-06/acid-fast-slide.jpg', 'A microscope field with bright pink acid-fast rods and blue non-acid-fast cells.', 'Acid-fast reference image supplied with Lesson 06');
  const simpleDifferential = figure('assets/lessons-03-06/simple-vs-differential.png', 'A comparison explaining that simple stains use one dye while differential stains use multiple dyes to distinguish cells or structures.', 'Simple and differential stain comparison from the instructor review');
  const negativeStain = figure('assets/lessons-03-06/negative-stain.png', 'Light unstained bacterial cells visible against a dark background produced by nigrosin.', 'Negative-stain image from the instructor review');
  const acidFastReview = figure('assets/lessons-03-06/acid-fast-review.png', 'Acid-fast stain with dark-blue non-acid-fast cells and pink acid-fast cells.', 'Acid-fast interpretation from the instructor review');
  const endosporeStain = figure('assets/lessons-03-06/endospore-stain.png', 'Green endospores within and outside pink vegetative bacilli after the Schaeffer-Fulton stain.', 'Endospore stain from the instructor review');
  const capsuleStain = figure('assets/lessons-03-06/capsule-stain.png', 'Purple bacterial cells surrounded by clear halos against a stained background.', 'Capsule-stain image from the instructor review');
  const specialStains = figure('assets/lessons-03-06/special-stain-identification.png', 'A comparison of acid-fast organisms, capsule-producing cells, and endospore-forming bacilli.', 'Specialized-structure identification from the instructor review');
  const acidFastComparison = figure('assets/lessons-03-06/acid-fast-comparison.png', 'Several acid-fast stained fields with bright red or pink rods among blue cells.', 'Acid-fast comparison fields from the instructor review');

  window.MICROLAB_QUESTIONS_56 = [
    mcq('L56-E-001','easy',5,'Smear preparation','LM05 Note lines 47-52','What is a bacterial smear?',['A thin specimen applied to a slide for staining','A colony growing on agar','A liquid culture in broth','A disinfected microscope lens'],'A thin specimen applied to a slide for staining','A smear places bacteria in a thin film on a glass slide before staining.'),
    mcq('L56-E-002','easy',5,'Heat fixation','LM05 Note lines 48-52 and 203-206','Which is a function of heat fixing a bacterial smear?',['Attach cells to the slide','Create isolated colonies','Increase broth turbidity','Remove every cell wall'],'Attach cells to the slide','Heat fixing promotes adherence, slightly disrupts cell walls for dye entry, and may kill cells.'),
    mcq('L56-E-003','easy',5,'Smear preparation','LM05 Note lines 60-74','What should be added before preparing a smear from a solid agar culture?',['A small drop of water','Gram iodine','Acid-alcohol','Immersion oil'],'A small drop of water','A tiny amount of the dense solid culture is dispersed in water to produce a thin smear.'),
    mcq('L56-E-004','easy',5,'Smear drying','LM05 Note lines 75-78 and 196-206','What must happen before a smear is heat fixed?',['It must air dry completely','It must be covered with oil','It must be incubated overnight','It must be mixed with agar'],'It must air dry completely','Heating a wet smear can distort or burst cells.'),
    mcq('L56-E-005','easy',5,'Simple stain','LM05 Note lines 3-7','How many dyes are used in a simple stain?',['One','Two','Three','Four'],'One','A simple stain uses a single dye to reveal general morphology.'),
    mcq('L56-E-006','easy',5,'Differential stain','LM05 Note lines 5-7','What distinguishes a differential stain from a simple stain?',['It uses more than one dye to reveal differences','It never uses a slide','It stains only the background','It requires no specimen'],'It uses more than one dye to reveal differences','Differential stains separate cells or structures into visibly different groups.'),
    mcq('L56-E-007','easy',5,'Positive staining','LM05 Note lines 83-92 and 210-216','Why do basic dyes stain most bacterial cells?',['Their positive chromophores are attracted to negatively charged cell surfaces','Their negative chromophores dissolve the cell wall','They repel every cell surface','They contain agar that traps bacteria'],'Their positive chromophores are attracted to negatively charged cell surfaces','Opposite charges attract, so basic dyes bind to the generally negative cell surface.'),
    mcq('L56-E-008','easy',5,'Negative staining','LM05 Note lines 143-151 and 218-222','What does a negative stain color?',['The background','The bacterial cells only','The microscope objective','The agar medium'],'The background','The negatively charged acidic dye is repelled by the cell surface and stains the surrounding field.'),
    mcq('L56-E-009','easy',5,'Simple-stain reagent','LM05 PDF p.2','Which dye is used in the course simple-stain procedure?',['Methylene blue','Malachite green','Carbol fuchsin','Gram iodine'],'Methylene blue','Methylene blue is a basic positive dye used to stain the cells.'),
    mcq('L56-E-010','easy',5,'Negative-stain reagent','LM05 PDF pp.3-4','Which reagent is used for the negative stain?',['Nigrosin or India ink','Safranin only','Gram iodine','Acid-alcohol'],'Nigrosin or India ink','Nigrosin and India ink are acidic dyes that darken the background.'),
    mcq('L56-E-011','easy',5,'Gram stain','LM05 Note lines 105-142','What is the primary stain in the Gram-stain procedure?',['Crystal violet','Safranin','Gram iodine','Alcohol'],'Crystal violet','Crystal violet colors all cells purple at the beginning of the procedure.'),
    mcq('L56-E-012','easy',5,'Gram stain','LM05 Note lines 114-129','What is the mordant in the Gram stain?',['Gram iodine','Crystal violet','Safranin','Water'],'Gram iodine','Iodine helps fix the crystal-violet complex within the cell wall.'),
    mcq('L56-E-013','easy',5,'Gram stain','LM05 Note lines 120-129','What is the counterstain in the Gram stain?',['Safranin','Crystal violet','Acid-alcohol','Nigrosin'],'Safranin','Safranin colors cells that became colorless during decolorization.'),
    mcq('L56-E-014','easy',5,'Gram reaction','LM05 Note lines 231-233','What color are correctly stained Gram-positive cells?',['Purple','Pink or red','Green','Colorless'],'Purple','The thick peptidoglycan layer retains the crystal-violet iodine complex.'),
    mcq('L56-E-015','easy',5,'Gram reaction','LM05 Note lines 231-233','What color are correctly stained Gram-negative cells?',['Pink or red','Purple','Green','Black'],'Pink or red','Alcohol removes crystal violet from Gram-negative cells, which then take up safranin.'),
    mcq('L56-E-016','easy',6,'Capsules','LM06 Note lines 327-355 and 543-554','How does a bacterial capsule commonly contribute to pathogenicity?',['It helps the cell resist phagocytosis','It produces ATP for the host','It replaces the chromosome','It makes the cell Gram negative'],'It helps the cell resist phagocytosis','The capsule can hide bacterial surface signals and help cells attach and evade immune clearance.'),
    mcq('L56-E-017','easy',6,'Endospores','LM06 Note lines 357-381 and 557-566','What is an endospore?',['A highly resistant, metabolically inactive bacterial structure','A reproductive fungal spore','A Gram-negative outer membrane','A bacterial flagellum'],'A highly resistant, metabolically inactive bacterial structure','Endospores protect certain Gram-positive bacilli during unfavorable conditions.'),
    mcq('L56-E-018','easy',6,'Acid-fast cells','LM06 Note lines 382-415 and 570-573','Which cell-wall component makes acid-fast organisms waxy and difficult to stain?',['Mycolic acid','Cellulose','Chitin','Lipoteichoic acid only'],'Mycolic acid','Waxy mycolic acids resist water-based dyes and decolorization.'),
    mcq('L56-E-019','easy',6,'Flagella','LM06 Note lines 416-437 and 579-581','What does monotrichous mean?',['One flagellum at one pole','A flagellum at each pole','Many flagella over the surface','No flagella'],'One flagellum at one pole','Mono- means one; monotrichous cells have a single polar flagellum.'),
    mcq('L56-E-020','easy',6,'Motility medium','LM06 Note lines 493-519 and 599-605','What indicates a positive motility result in TTC semisolid agar?',['Red growth radiating away from the stab line','A thin red line confined to the stab','A completely colorless tube','A green endospore inside every cell'],'Red growth radiating away from the stab line','Motile cells spread from the inoculation path, and reduced TTC makes their growth red.'),

    mcq('L56-M-001','medium',5,'Broth smear','LM05 Note lines 60-63 and 191-195','Why are one or two loopfuls from a broth culture placed in a small area on the slide?',['Liquid samples usually contain fewer cells and should be concentrated','Broth cells cannot be heat fixed','The slide must remain completely dry from the start','Water would make the cells Gram positive'],'Liquid samples usually contain fewer cells and should be concentrated','Concentrating a small liquid sample improves the chance of seeing enough cells.'),
    mcq('L56-M-002','medium',5,'Solid-culture smear','LM05 Note lines 64-74 and 193-195','Why is only a tiny amount of growth taken from solid agar for a smear?',['Solid cultures are very dense and must be diluted into water','Agar cultures contain no bacteria','The loop cannot touch water','A thick smear always decolorizes evenly'],'Solid cultures are very dense and must be diluted into water','Too much material produces clumps, uneven staining, and unreliable interpretation.'),
    mcq('L56-M-003','medium',5,'Smear quality','LM05 PDF p.4 review question 1','Why should a Gram-stain smear be thin and uniform?',['So stains and decolorizer act evenly throughout the specimen','So no cells attach to the slide','So heat fixing can be skipped','So every bacterium appears Gram positive'],'So stains and decolorizer act evenly throughout the specimen','Thickness changes dye retention and decolorization, making the result misleading.'),
    mcq('L56-M-004','medium',5,'Gram-stain sequence','LM05 Note lines 111-132','Which sequence is correct for the Gram stain?',['Crystal violet → iodine → decolorizer → safranin','Safranin → iodine → crystal violet → water','Iodine → acid-alcohol → malachite green → safranin','Nigrosin → crystal violet → copper sulfate → water'],'Crystal violet → iodine → decolorizer → safranin','Primary stain is followed by mordant, controlled decolorization, and counterstain.'),
    mcq('L56-M-005','medium',5,'Gram decolorization','LM05 Note lines 120-127 and 227-233','What should happen immediately after the decolorizer runoff becomes clear?',['Rinse with water to stop decolorization','Allow the slide to dry in alcohol','Add more crystal violet','Heat the wet slide'],'Rinse with water to stop decolorization','Water halts the critical decolorization step before Gram-positive cells lose their primary stain.'),
    mcq('L56-M-006','medium',5,'Gram-positive wall','LM05 Note lines 231-233','Why do Gram-positive cells retain crystal violet after alcohol treatment?',['Their thick peptidoglycan traps the dye complex','Their outer membrane dissolves into a blue pigment','They contain mycolic acid','They have no cell wall'],'Their thick peptidoglycan traps the dye complex','Multiple peptidoglycan layers retain the crystal-violet iodine complex.'),
    mcq('L56-M-007','medium',5,'Gram-negative wall','LM05 Note lines 231-233','Why do Gram-negative cells become colorless during decolorization?',['Alcohol disrupts the outer membrane and the thin peptidoglycan does not retain the dye complex','Their thick peptidoglycan blocks safranin','They contain endospores','They have no plasma membrane'],'Alcohol disrupts the outer membrane and the thin peptidoglycan does not retain the dye complex','Loss of the primary stain allows Gram-negative cells to take up safranin.'),
    mcq('L56-M-008','medium',5,'Gram-stain quality','LM05 Note lines 235-247','Why can an old culture produce a Gram-variable result?',['Aging cell walls decolorize inconsistently and cells may lyse','Old cells always produce capsules','Old cells cannot bind any dye at all','Old cultures contain only eukaryotic cells'],'Aging cell walls decolorize inconsistently and cells may lyse','Culture age can weaken cell-wall integrity and make the Gram reaction unreliable.'),
    short('L56-M-009','medium',5,'Stain comparison','Study Guide LM05 · Instructor review slide 25','Which category of stain uses two or more dyes to distinguish groups of cells or cell structures?',['differential stain','differential staining'],'Differential stain','Differential staining uses multiple reagents to reveal structural or biochemical differences.',simpleDifferential),
    short('L56-M-010','medium',5,'Negative stain','LM05 PDF pp.3-4 · Instructor review slide 34','Name the staining method shown, where colorless cells appear against a dark background.',['negative stain','negative staining','nigrosin stain'],'Negative stain','An acidic dye such as nigrosin stains the background while cells remain unstained.',negativeStain),
    mcq('L56-M-011','medium',6,'Capsule stain','LM06 Note lines 334-347','Why must a capsule-stain smear not be heat fixed?',['Heat can shrink or destroy the capsule and allow dye penetration','Heat would make every cell acid-fast','Heat prevents crystal violet from entering cells','Heat converts copper sulfate into agar'],'Heat can shrink or destroy the capsule and allow dye penetration','Preserving the delicate, non-ionic capsule is essential for seeing a clear halo.'),
    mcq('L56-M-012','medium',6,'Capsule stain','LM06 Note lines 339-352 and 550-554','What is the role of 20% copper sulfate in the course capsule stain?',['It removes excess crystal violet and counterstains the background without water rinsing','It is the primary stain for endospores','It decolorizes acid-fast cells','It heat-fixes the capsule'],'It removes excess crystal violet and counterstains the background without water rinsing','Copper sulfate clears dye from capsule material while leaving stained cells and background contrast.'),
    mcq('L56-M-013','medium',6,'Endospore stain','LM06 Note lines 363-374','Which reagents and final colors are correct for the endospore stain?',['Malachite green makes spores green; safranin makes vegetative cells pink','Crystal violet makes spores purple; iodine makes cells black','Carbol fuchsin makes spores blue; methylene blue makes cells red','Nigrosin makes spores colorless; water makes cells green'],'Malachite green makes spores green; safranin makes vegetative cells pink','Steam drives malachite green into spores, and safranin counterstains vegetative cells.'),
    mcq('L56-M-014','medium',6,'Endospore stain','LM06 Note lines 364-369 and 566','Why is steam used during endospore staining?',['It acts as a mordant that drives malachite green through the resistant spore coat','It dissolves every vegetative cell','It turns TTC red','It prevents the slide from receiving stain'],'It acts as a mordant that drives malachite green through the resistant spore coat','The tough spore coat requires heat to admit the primary stain.'),
    mcq('L56-M-015','medium',6,'Acid-fast stain','LM06 Note lines 395-410','Which reagent combination is correct for the acid-fast stain?',['Carbol fuchsin, acid-alcohol, and methylene blue','Crystal violet, iodine, and safranin only','Malachite green, water, and safranin','Nigrosin and copper sulfate'],'Carbol fuchsin, acid-alcohol, and methylene blue','Carbol fuchsin is driven into waxy cells, acid-alcohol decolorizes non-acid-fast cells, and methylene blue counterstains them.'),
    mcq('L56-M-016','medium',6,'Acid-fast interpretation','LM06 Note lines 404-410','What colors indicate a correctly performed acid-fast stain?',['Acid-fast cells hot pink; non-acid-fast cells blue','Acid-fast cells green; non-acid-fast cells pink','Acid-fast cells purple; non-acid-fast cells colorless','All cells black'],'Acid-fast cells hot pink; non-acid-fast cells blue','Acid-fast organisms retain carbol fuchsin, while decolorized cells take up methylene blue.'),
    mcq('L56-M-017','medium',6,'Flagellar arrangements','LM06 Note lines 579-581','A bacterium has one flagellum at each pole. What is the arrangement?',['Amphitrichous','Monotrichous','Lophotrichous','Peritrichous'],'Amphitrichous','Amphi- indicates flagella at both ends.'),
    mcq('L56-M-018','medium',6,'Wet mounts','LM06 Note lines 583-590','What microscope adjustment improves contrast when viewing transparent living cells in a brightfield wet mount?',['Reduce illumination by closing the iris and lowering the condenser','Open the iris fully and raise the condenser','Heat-fix the wet mount','Add crystal violet to every wet mount'],'Reduce illumination by closing the iris and lowering the condenser','Limiting light helps transparent living cells stand out from the bright background.'),
    mcq('L56-M-019','medium',6,'Brownian motion','LM06 Note lines 587-590','Which observation is most consistent with Brownian motion?',['Cells vibrate in place because water molecules collide with them','Cells travel in directed runs and tumbles over long distances','Red growth radiates away from a stab line','Cells remain fixed to a heat-fixed slide'],'Cells vibrate in place because water molecules collide with them','Brownian motion is local vibration, not self-propelled movement.'),
    mcq('L56-M-020','medium',6,'Motility stab','LM06 Note lines 493-519','Why must a motility-agar inoculation be a single straight stab down and back along the same path?',['A clean path makes spreading away from the line interpretable as motility','Multiple angled stabs make TTC colorless','A straight stab heat-fixes the cells','The needle must cut the tube wall'],'A clean path makes spreading away from the line interpretable as motility','A wandering inoculation path can mimic lateral growth and create a false-positive interpretation.'),

    mcq('L56-H-001','hard',5,'Gram-stain error','LM05 PDF p.4 review question 3','What is the likely result of over-decolorizing a Gram-positive culture?',['False Gram-negative or pink cells','Darker purple cells','Green endospores','No effect on color'],'False Gram-negative or pink cells','Excess alcohol removes crystal violet even from Gram-positive cells, allowing safranin to dominate.'),
    mcq('L56-H-002','hard',5,'Gram-stain error','LM05 PDF p.4 review question 3','What is the likely result of under-decolorizing Gram-negative cells?',['They may remain falsely purple','They become green','They become invisible because safranin is removed','They form endospores'],'They may remain falsely purple','Residual crystal violet can mask the expected Gram-negative pink reaction.'),
    mcq('L56-H-003','hard',5,'Gram-stain error','LM05 PDF p.4 review question 3','What is the likely effect of omitting Gram iodine?',['The crystal-violet complex is not fixed well, so Gram-positive cells may decolorize falsely','Gram-negative cells become acid-fast','All cells become green','Safranin can no longer enter Gram-negative cells'],'The crystal-violet complex is not fixed well, so Gram-positive cells may decolorize falsely','Without the mordant, the primary stain is not retained reliably.'),
    mcq('L56-H-004','hard',5,'Gram-stain error','LM05 PDF p.4 review question 3','If safranin is omitted after correct decolorization, what happens?',['Gram-negative cells remain colorless while Gram-positive cells remain purple','All cells become pink','Gram-positive cells become colorless and Gram-negative cells purple','Every cell becomes green'],'Gram-negative cells remain colorless while Gram-positive cells remain purple','Safranin is needed to visualize the decolorized Gram-negative cells.'),
    mcq('L56-H-005','hard',5,'Gram-stain error','LM05 Note lines 235-247','Why can a very thick smear make Gram-negative cells appear falsely Gram positive?',['Cell clumps retain crystal violet and decolorize unevenly','Thick smears remove all peptidoglycan','Safranin becomes a mordant','The cells develop capsules immediately'],'Cell clumps retain crystal violet and decolorize unevenly','Excess material traps dye and prevents uniform action of the decolorizer.'),
    mcq('L56-H-006','hard',5,'Culture purity','Study Guide LM05 · LM05 Note lines 25 and 255-257','A plate has colonies with identical appearance, but the Gram-stained sample contains purple cocci and pink rods. What is the best conclusion?',['The culture is mixed or contaminated','The culture is proven pure','The cells are all Gram variable','The plate contains only eukaryotic cells'],'The culture is mixed or contaminated','Purity requires consistent cellular morphology and Gram reaction, not colony appearance alone.'),
    short('L56-H-007','hard',5,'Gram-stain sequence','LM05 supplied Gram-process figure','Which reagent is applied at Step 2 as the mordant?',['gram iodine','iodine','grams iodine'],'Gram iodine','Iodine forms a less soluble complex with crystal violet and helps retain it in the cell wall.',gramProcess),
    short('L56-H-008','hard',5,'Negative staining','LM05 PDF pp.3-4 · Instructor review slide 34','Which acidic dye is specifically named for the dark-background preparation shown?',['nigrosin','nigrosin dye'],'Nigrosin','Nigrosin is negatively charged and is repelled by bacterial cell surfaces.',negativeStain),
    mcq('L56-H-009','hard',6,'Capsule stain','LM06 Note lines 343-352 and 548-554','Why does the capsule protocol avoid a water rinse after crystal violet?',['Water can alter or remove the water-soluble capsule and destroy the halo','Water would convert cells into endospores','Water would make mycolic acid thicker','Water is the primary capsule stain'],'Water can alter or remove the water-soluble capsule and destroy the halo','Copper sulfate replaces the water rinse so the non-ionic capsule remains visible.'),
    short('L56-H-010','hard',6,'Capsule identification','Study Guide LM06 · Instructor review slide 38','What clear structure surrounds the stained cells in the image?',['capsule','capsules','bacterial capsule','glycocalyx'],'Capsule','Capsules remain as clear halos because the cell and background stain while capsular material does not.',capsuleStain),
    mcq('L56-H-011','hard',6,'Endospore reliability','LM06 PDF p.6 review question 6','A 24-hour Gram-positive bacillus gives a negative endospore stain. Why is the result not conclusive?',['A young culture may not have encountered conditions that induce sporulation','Endospores occur only in Gram-negative cocci','Safranin destroys all endospores','Endospores can be seen only in broth'],'A young culture may not have encountered conditions that induce sporulation','Testing an older culture or inducing nutrient limitation may reveal spores that were absent in young growth.'),
    mcq('L56-H-012','hard',6,'Endospore location','LM06 Note lines 564-566','An endospore lies between the center and the end of a vegetative cell. How is its position described?',['Subterminal','Central','Terminal','Peritrichous'],'Subterminal','Subterminal spores are located between the middle and one pole.'),
    short('L56-H-013','hard',6,'Endospore identification','LM06 supplied endospore-process figure','After the complete Schaeffer-Fulton stain, what color should an endospore be?',['green','malachite green'],'Green','Steam drives malachite green into the resistant spore; water removes it from vegetative cells.',endosporeProcess),
    mcq('L56-H-014','hard',6,'Endospore diseases','LM06 Note lines 357-362 and 557-565','Which organism-disease pairing is correct?',['Clostridium tetani — tetanus','Bacillus anthracis — leprosy','Mycobacterium tuberculosis — botulism','Streptococcus pneumoniae — anthrax'],'Clostridium tetani — tetanus','Important endospore formers include Bacillus anthracis and Clostridium species causing tetanus and botulism.'),
    short('L56-H-015','hard',6,'Acid-fast identification','LM06 supplied acid-fast figure','What color identifies acid-fast-positive cells in this field?',['pink','hot pink','red','reddish pink'],'Hot pink','Acid-fast cells retain carbol fuchsin after acid-alcohol treatment.',acidFastSlide),
    mcq('L56-H-016','hard',6,'Acid-fast test selection','LM06 PDF p.6 review question 1','When is an acid-fast stain more useful than a Gram stain?',['When Mycobacterium or another organism with waxy mycolic acids is suspected','For every routine bacterial specimen','Only when viewing a fungal wet mount','When testing colony pigmentation'],'When Mycobacterium or another organism with waxy mycolic acids is suspected','Mycolic-acid-rich walls resist the aqueous reagents used in the Gram stain.'),
    mcq('L56-H-017','hard',6,'Acid-fast diseases','LM06 Note lines 382-394 and 570-573','Which medically important organisms are acid-fast?',['Mycobacterium tuberculosis and Mycobacterium leprae','Bacillus anthracis and Clostridium tetani','Streptococcus pneumoniae and Klebsiella pneumoniae','Lactobacillus and Corynebacterium only'],'Mycobacterium tuberculosis and Mycobacterium leprae','These acid-fast species cause tuberculosis and leprosy.'),
    short('L56-H-018','hard',6,'Special-stain interpretation','Study Guide LM06 · Instructor review slide 39','Which specialized stain is represented by bright pink rods among blue non-acid-fast cells?',['acid-fast stain','acid fast stain','ziehl-neelsen stain','ziehl neelsen'],'Acid-fast stain','Acid-fast rods retain carbol fuchsin while other cells take up methylene blue.',specialStains),
    mcq('L56-H-019','hard',6,'Motility interpretation','LM06 Note lines 587-590','A wet-mount cell repeatedly travels across the field in runs followed by abrupt changes in direction. What is the best interpretation?',['True motility','Brownian motion','A heat-fix artifact','Negative motility because it changes direction'],'True motility','Flagellar motility produces movement over meaningful distances with runs and tumbles.'),
    mcq('L56-H-020','hard',6,'Motility agar control','LM06 PDF pp.5-6 · Note lines 493-519','A TTC motility tube shows a wide red haze, but the inoculating needle entered at several angles. What is the best conclusion?',['The result is unreliable because the inoculation path can mimic spreading','The organism is definitively motile','The organism is definitively non-motile','TTC proves the culture is pure'],'The result is unreliable because the inoculation path can mimic spreading','A single clean stab is required before growth away from that path can be attributed to motility.'),
    short('L56-H-021','hard',6,'Acid-fast comparison','Study Guide LM06 · Instructor review slide 43','What stain produced the red rods visible in the figure?',['acid-fast stain','acid fast stain','ziehl-neelsen stain','ziehl neelsen'],'Acid-fast stain','Carbol fuchsin remains in acid-fast cells after acid-alcohol decolorization.',acidFastComparison)
  ];
})();
