(() => {
  const figure = (src, alt, caption) => `<figure class="figure-box"><img src="${src}" alt="${alt}"><figcaption>${caption}</figcaption></figure>`;
  const mcq = (id, level, module, topic, source, prompt, options, answer, explanation, image = '') => ({ id, level, module, type:'mcq', topic, source, prompt, options, answer, explanation, figure:image });
  const short = (id, level, module, topic, source, prompt, answers, displayAnswer, explanation, image = '') => ({ id, level, module, type:'short', topic, source, prompt, answers, displayAnswer, explanation, figure:image });
  const microscope = figure('assets/lessons-03-06/compound-microscope.jpg', 'A labeled compound light microscope showing ocular lenses, nosepiece, objectives, stage, iris diaphragm, condenser, light, and focusing knobs.', 'Compound microscope reference supplied with Lessons 03 and 04');
  const microscopyTypes = figure('assets/lessons-03-06/microscopy-types.jpg', 'A comparison chart showing brightfield, phase-contrast, fluorescence, scanning electron, and transmission electron microscopy.', 'Microscopy comparison supplied with Lesson 03');
  const shapes = figure('assets/lessons-03-06/cell-shapes-arrangements.png', 'Examples of cocci and bacilli in pairs, chains, tetrads, sarcinae, clusters, and palisades, plus curved and spiral cells.', 'Cell shapes and arrangements from the instructor review');
  const media = figure('assets/lessons-03-06/culture-media.png', 'Agar plate, agar deep tube, broth tube, and agar slant used to culture bacteria.', 'Culture-media formats from the instructor review');
  const streak = figure('assets/lessons-03-06/streak-isolation.png', 'A T-streak diagram showing successive streak areas and an agar plate with isolated colonies.', 'Pure-culture streak isolation from the instructor review');

  window.MICROLAB_QUESTIONS_34 = [
    mcq('L34-E-001','easy',3,'Brightfield microscopy','LM03 Note lines 252-253','Why is this microscope called a brightfield microscope?',['The specimen is surrounded by a bright background','It uses only ultraviolet light','It produces a three-dimensional surface image','It has no condenser'],'The specimen is surrounded by a bright background','Light passes through the specimen and produces contrast against a bright field.'),
    mcq('L34-E-002','easy',3,'Darkfield microscopy','LM03 Note lines 256-257','How does a specimen normally appear in darkfield microscopy?',['Bright against a dark background','Dark against a bright background','Purple against a pink background','Colorless against a white background'],'Bright against a dark background','Only light scattered by the specimen enters the objective, making the specimen bright on a dark field.'),
    mcq('L34-E-003','easy',3,'Phase-contrast microscopy','LM03 Note lines 258-260','What is a major advantage of phase-contrast microscopy?',['Living unstained cells can be viewed in their natural state','Only dead cells can be examined','It produces only surface images','It requires fluorescent antibodies'],'Living unstained cells can be viewed in their natural state','Phase contrast converts phase differences into visible contrast without requiring heat fixation or staining.'),
    mcq('L34-E-004','easy',3,'Fluorescence microscopy','LM03 Note lines 261-263','What molecules produce the visible signal in fluorescence microscopy?',['Fluorophores','Agar molecules','Peptidoglycan layers','Immersion-oil droplets'],'Fluorophores','Fluorophores absorb light at one wavelength and emit visible light at another.'),
    mcq('L34-E-005','easy',3,'Electron microscopy','LM03 Note line 265','Which electron microscope produces a detailed three-dimensional view of a specimen surface?',['Scanning electron microscope','Transmission electron microscope','Brightfield microscope','Phase-contrast microscope'],'Scanning electron microscope','SEM scans the surface with electrons to produce detailed surface images.'),
    mcq('L34-E-006','easy',3,'Electron microscopy','LM03 Note line 265','Which electron microscope is used to visualize internal ultrastructure?',['Transmission electron microscope','Scanning electron microscope','Dissecting microscope','Darkfield microscope'],'Transmission electron microscope','TEM passes a fine electron beam through the specimen to reveal internal structure.'),
    mcq('L34-E-007','easy',3,'Microscope magnification','LM03 Note lines 203-207','What is the magnification of the standard ocular lens described in the course?',['10×','4×','40×','100×'],'10×','The binocular compound microscope uses 10× ocular lenses.'),
    mcq('L34-E-008','easy',3,'Microscope objectives','LM03 Note line 205','Which objective is the scanning objective?',['4×','10×','40×','100×'],'4×','The course microscope uses 4× scanning, 10× low-power, 40× high-power, and 100× oil-immersion objectives.'),
    mcq('L34-E-009','easy',3,'Total magnification','LM03 Note line 207','How is total magnification calculated?',['Ocular magnification × objective magnification','Ocular magnification + objective magnification','Objective magnification ÷ ocular magnification','Condenser power × objective magnification'],'Ocular magnification × objective magnification','Total magnification is the product of ocular and objective powers.'),
    mcq('L34-E-010','easy',3,'Parfocal microscope','LM03 Note lines 205 and 281','What does parfocal mean?',['A specimen remains nearly focused when objectives are changed','The specimen remains centered when objectives are changed','The image is always upright','Both oculars have identical power'],'A specimen remains nearly focused when objectives are changed','A parfocal microscope needs only minimal fine focusing after changing objectives.'),
    mcq('L34-E-011','easy',3,'Parcentral microscope','LM03 Note lines 205 and 237','What does parcentral mean?',['The centered specimen remains centered when objectives are changed','The specimen remains perfectly focused at every power','The condenser stays raised','The image becomes brighter automatically'],'The centered specimen remains centered when objectives are changed','Parcentral optics keep the selected point near the center as magnification changes.'),
    mcq('L34-E-012','easy',3,'Condenser','LM03 Note line 209','What is the main function of the condenser?',['Collect and direct light through the specimen','Magnify the specimen 10 times','Move the slide left and right','Hold the objective lenses'],'Collect and direct light through the specimen','The condenser focuses illumination onto the slide but does not add magnification.'),
    mcq('L34-E-013','easy',3,'Iris diaphragm','LM03 Note line 209','What does the iris diaphragm control?',['The amount of light entering the microscope','The magnification of the oculars','The position of the slide','The distance between ocular lenses'],'The amount of light entering the microscope','The iris diaphragm regulates illumination and contrast.'),
    mcq('L34-E-014','easy',3,'Cell morphology','LM03 Note lines 337-340','What is a spherical bacterial cell called?',['Coccus','Bacillus','Vibrio','Spirillum'],'Coccus','Coccus is the term for a spherical cell; the plural is cocci.'),
    mcq('L34-E-015','easy',3,'Cell morphology','LM03 Note line 341','What is a rod-shaped bacterial cell called?',['Bacillus','Coccus','Spirochete','Tetrad'],'Bacillus','Lowercase bacillus describes rod morphology; uppercase italic Bacillus is a genus.'),
    mcq('L34-E-016','easy',3,'Cell morphology','LM03 Note lines 343-347','What term describes a bent or curved rod?',['Vibrio','Coccobacillus','Sarcina','Staphylococcus'],'Vibrio','Vibrio cells are characteristically curved or bent rods.'),
    mcq('L34-E-017','easy',3,'Cell types','LM03 Note lines 297-305','Which feature distinguishes eukaryotic cells from prokaryotic cells?',['Membrane-bound organelles','A plasma membrane','DNA','Ribosomes'],'Membrane-bound organelles','Both cell types have membranes, DNA, cytoplasm, and ribosomes, but eukaryotes contain membrane-bound organelles.'),
    mcq('L34-E-018','easy',4,'Culture media','LM04 Note lines 536-542','What is culture medium?',['Material that supplies nutrients for microbial growth','A dye used for differential staining','A lens-cleaning solution','A chemical used only to kill microbes'],'Material that supplies nutrients for microbial growth','In vitro culture requires a medium that provides nutrients and suitable conditions for growth.'),
    mcq('L34-E-019','easy',4,'Broth medium','LM04 Note line 542','What is broth used primarily for?',['Growing and maintaining bacterial cultures','Separating individual colonies from a mixture','Viewing cells under oil immersion','Differentiating cells by Gram reaction'],'Growing and maintaining bacterial cultures','Broth is a liquid medium useful for growth and maintenance, but it cannot separate a mixed culture.'),
    mcq('L34-E-020','easy',4,'Pure culture','LM04 Note lines 708-710','What does a pure culture contain?',['One species of microorganism','Every organism in the original sample','Only nonpathogenic organisms','Only organisms that grow in broth'],'One species of microorganism','A pure culture originates from a single cell or isolated colony and contains one microbial species.'),

    mcq('L34-M-001','medium',3,'Virtual image','LM03 PDF pp.1-2 · Note lines 80-90','How does the microscope image of the letter “e” compare with the letter on the slide?',['It is inverted and reversed','It remains upright and unchanged','It rotates only 90 degrees','It becomes a real image on the stage'],'It is inverted and reversed','The lens system flips and reverses the image before it reaches the oculars.'),
    mcq('L34-M-002','medium',3,'Image movement','LM03 PDF p.2 · Note lines 91-95','If the slide is moved to the right, which way does the virtual image appear to move?',['Left','Right','Up only','It does not move'],'Left','Microscope image movement is opposite the physical movement of the slide.'),
    mcq('L34-M-003','medium',3,'High-power focusing','LM03 PDF p.3 · Note lines 105-117','Which focus control should be used with the 40× high-power objective?',['Fine adjustment only','Coarse adjustment only','Stage clips only','Interocular adjustment only'],'Fine adjustment only','The coarse knob can drive the high-power objective into the slide and damage both.'),
    mcq('L34-M-004','medium',3,'Oil immersion','LM03 Note lines 216 and 289-290','Why is immersion oil used with the 100× objective?',['It reduces refraction and improves resolution','It stains bacteria purple','It increases the ocular power','It keeps the slide from drying'],'It reduces refraction and improves resolution','Oil decreases the loss and bending of transmitted light before it enters the oil-immersion lens.'),
    mcq('L34-M-005','medium',3,'Working distance','LM03 Note lines 213 and 238','What happens to working distance as objective magnification increases?',['It decreases','It increases','It remains unchanged','It becomes equal to field of view'],'It decreases','Higher-power objectives focus closer to the slide.'),
    mcq('L34-M-006','medium',3,'Field of view','LM03 Note lines 237 and 277','What happens to field of view as magnification increases?',['It becomes smaller','It becomes larger','It becomes brighter without adjustment','It becomes a real image'],'It becomes smaller','Higher magnification shows a smaller portion of the specimen.'),
    mcq('L34-M-007','medium',3,'Depth of focus','LM03 Note lines 215 and 280','What happens to depth of focus as total magnification increases?',['It decreases','It increases','It remains constant','It becomes the same as working distance'],'It decreases','Less specimen thickness remains simultaneously in focus at higher magnification.'),
    mcq('L34-M-008','medium',3,'Eukaryotic microscopy','LM03 PDF pp.4-5 · Note lines 164-188','Why are large eukaryotic specimens often best observed with scanning or low-power objectives?',['Their thickness and size reduce useful depth of focus at high power','They cannot transmit any light','They are always smaller than bacteria','Oil makes their nuclei disappear'],'Their thickness and size reduce useful depth of focus at high power','Large specimens may not remain clear at high magnification because depth of focus decreases.'),
    short('L34-M-009','medium',3,'Microscope parts','LM03 supplied microscope figure','Identify the rotating part that holds the objective lenses.',['revolving nosepiece','nosepiece','rotating nosepiece','turret'],'Revolving nosepiece','The revolving nosepiece holds the objectives and is used to change magnification.',microscope),
    short('L34-M-010','medium',3,'Microscopy types','LM03 supplied microscopy comparison','Which microscopy method in the figure uses electrons to create a detailed three-dimensional surface view?',['scanning electron microscopy','scanning electron microscope','sem'],'Scanning electron microscopy (SEM)','SEM scans the specimen surface with a focused electron beam.',microscopyTypes),
    mcq('L34-M-011','medium',4,'Aseptic technique','LM04 Note lines 561-571','Aseptic technique is designed to protect which three targets?',['The worker, the culture, and the environment','Only the culture','Only the laboratory worker','Only the incubator'],'The worker, the culture, and the environment','Good technique limits exposure of workers and surroundings while preventing unwanted contamination of cultures.'),
    mcq('L34-M-012','medium',4,'Loop sterilization','LM04 PDF p.1 · Note lines 411-421','After an inoculating loop glows orange in the incinerator, what should happen before collecting inoculum?',['Allow it to cool for about 15 seconds','Dip it in disinfectant','Set it on the bench','Immediately place it in the culture'],'Allow it to cool for about 15 seconds','A hot loop may kill the cells being transferred and can cause splatter.'),
    mcq('L34-M-013','medium',4,'Tube handling','LM04 PDF p.1 · Note lines 427-434','Where should the tube cap be held during an aseptic transfer?',['With the little and ring fingers of the loop hand','On the disinfected bench','Inside the test-tube rack','Between the teeth'],'With the little and ring fingers of the loop hand','Keeping the cap in the hand prevents its sterile surface from contacting the bench.'),
    mcq('L34-M-014','medium',4,'Tube handling','LM04 Note lines 603-617','Why is an open culture tube held at a slight angle?',['To reduce entry of airborne contaminants','To increase evaporation','To make the broth darker','To keep the cap warm'],'To reduce entry of airborne contaminants','Angling the tube limits direct exposure of its opening to settling particles.'),
    mcq('L34-M-015','medium',4,'Tube flaming','LM04 Note lines 614-626 and 672','Why is the mouth of a culture tube heated during transfer?',['To create an outward warm-air current that reduces contamination','To boil the entire culture','To increase bacterial growth','To stain the tube opening'],'To create an outward warm-air current that reduces contamination','Heating the tube mouth promotes an updraft and reduces entry of airborne material.'),
    mcq('L34-M-016','medium',4,'Plate incubation','LM04 Note lines 680-681','Why are inoculated agar plates incubated upside down?',['To prevent lid condensation from dripping onto the agar','To expose colonies to more oxygen','To make agar melt evenly','To keep labels hidden'],'To prevent lid condensation from dripping onto the agar','Condensation can spread cells, mix colonies, disrupt isolation, and increase contamination risk.'),
    mcq('L34-M-017','medium',4,'Quadrant streak','LM04 PDF pp.2-3','What must be done before streaking each new quadrant after quadrant 1?',['Sterilize and cool the loop','Add fresh broth to the plate','Replace the agar plate','Heat-fix the colonies'],'Sterilize and cool the loop','Sterilizing between sectors produces progressive dilution; cooling prevents damage to cells and agar.'),
    mcq('L34-M-018','medium',4,'T-streak','LM04 PDF pp.3-4','In the course T-streak method, how many times should the loop cross from one completed section into the next?',['Three times','Once','Ten times','It should never cross'],'Three times','The protocol carries over three streaks, then continues in the new section without returning to the previous pattern.'),
    mcq('L34-M-019','medium',4,'Broth culture','LM04 PDF p.5','What visible observation indicates bacterial growth in broth?',['Turbidity','An isolated colony','A clear halo around every cell','A purple Gram reaction'],'Turbidity','Growth suspended in liquid makes the broth cloudy.'),
    mcq('L34-M-020','medium',4,'Agar slants','LM04 PDF p.6 · Note line 542','Why are agar slants useful for pure cultures?',['They support dense growth and longer refrigerated storage with less drying','They separate mixed cultures into isolated colonies better than plates','They are used only for motility testing','They eliminate the need for aseptic technique'],'They support dense growth and longer refrigerated storage with less drying','Slants provide a protected solid surface suited to maintenance, transport, and storage.'),

    mcq('L34-H-001','hard',3,'Magnification calculation','LM03 PDF p.5 review question 1','A specimen is viewed with a 15× ocular and a 40× objective. What is the total magnification?',['600×','400×','55×','6,000×'],'600×','15 × 40 = 600 total magnification.'),
    mcq('L34-H-002','hard',3,'Microscope troubleshooting','LM03 PDF p.5 review question 2','Half of the field is dark immediately after changing objectives. What should be checked first?',['Whether the objective is fully clicked into position','Whether the slide was heat-fixed','Whether the culture is pure','Whether the ocular is 100×'],'Whether the objective is fully clicked into position','A partially engaged objective commonly blocks part of the light path.'),
    mcq('L34-H-003','hard',3,'Microscope troubleshooting','LM03 PDF p.5 review question 2','A student sees two separate circular fields through the binocular oculars. What adjustment is needed?',['Adjust the interocular distance until one field is seen','Increase objective magnification','Add immersion oil','Lower the stage completely'],'Adjust the interocular distance until one field is seen','The ocular spacing must match the distance between the viewer’s eyes.'),
    mcq('L34-H-004','hard',3,'Microscope troubleshooting','LM03 PDF p.3 · Note lines 116-117','The specimen disappears after switching from 10× to 40×. What is the safest next step?',['Return to low power, refocus and recenter, then try 40× again','Use the coarse knob rapidly at 40×','Add oil to the 40× objective','Remove the ocular lens'],'Return to low power, refocus and recenter, then try 40× again','The smaller high-power field requires the target to be focused and centered first.'),
    mcq('L34-H-005','hard',3,'Oil immersion error','LM03 Note lines 216 and 242-249','What is the best response if oil accidentally contacts a non-oil objective?',['Clean it promptly with lens paper','Leave the oil so the lens remains lubricated','Wipe it with a regular paper towel','Immerse every objective in oil'],'Clean it promptly with lens paper','Only the 100× oil objective is designed for oil, and lenses must be cleaned with lens paper.'),
    mcq('L34-H-006','hard',3,'Electron microscopy','LM03 Note line 265','Which comparison between SEM and TEM is correct?',['SEM emphasizes surface topography; TEM reveals internal structure','SEM uses visible light; TEM uses ultraviolet light','SEM is for living wet mounts; TEM is for unstained cells','SEM has lower resolution than a classroom brightfield microscope'],'SEM emphasizes surface topography; TEM reveals internal structure','Both use electrons, but SEM scans surfaces and TEM passes electrons through thin specimens.'),
    mcq('L34-H-007','hard',3,'Cell size','LM03 Note lines 307-313','Why do smaller cells generally exchange materials more efficiently than larger cells of the same shape?',['They have a higher surface-area-to-volume ratio','They contain no cytoplasm','Their volume increases only with radius squared','They never require diffusion'],'They have a higher surface-area-to-volume ratio','Surface area scales with radius squared while volume scales with radius cubed.'),
    short('L34-H-008','hard',3,'Cell arrangements','LM03 Note lines 352-362 · Instructor review slide 14','What arrangement name describes four cocci produced by division in two planes?',['tetrad','tetrads'],'Tetrad','Two planes of division can produce a group of four cocci.',shapes),
    short('L34-H-009','hard',3,'Cell arrangements','LM03 Note lines 358-360 · Instructor review slide 14','What arrangement name describes irregular grape-like clusters of cocci?',['staphylococcus','staphylococci','staphylo','staphylo arrangement'],'Staphylococcus arrangement','Random planes of division produce irregular clusters.',shapes),
    short('L34-H-010','hard',3,'Cell arrangements','LM03 Note line 362 · Instructor review slide 14','What arrangement describes rod-shaped cells aligned side by side like a picket fence?',['palisade','palisades','palisade arrangement'],'Palisade arrangement','Palisade bacilli remain loosely connected at irregular points and align side by side.',shapes),
    mcq('L34-H-011','hard',4,'Culture purity','LM04 Note lines 729-733','Which evidence best supports that a culture is pure?',['Consistent colony morphology plus identical cell shape, arrangement, size, and Gram reaction','Visible turbidity in broth alone','Growth anywhere on an agar plate','A strong odor from the culture'],'Consistent colony morphology plus identical cell shape, arrangement, size, and Gram reaction','Purity is evaluated using both cultural and cellular characteristics.'),
    mcq('L34-H-012','hard',4,'Selective and differential media','LM04 Note lines 544-555','What is the defining difference between selective and differential media?',['Selective media inhibit some organisms; differential media reveal biochemical differences','Selective media are always liquid; differential media are always solid','Selective media kill all cells; differential media grow none','Selective media contain blood; differential media contain only water'],'Selective media inhibit some organisms; differential media reveal biochemical differences','Selective agents favor certain organisms, while indicators or substrates distinguish metabolic traits.'),
    mcq('L34-H-013','hard',4,'PEA medium','LM04 Note line 550','Why can phenylethyl alcohol agar help isolate Gram-positive bacteria from a mixed specimen?',['It inhibits most Gram-negative bacteria by interfering with DNA synthesis','It stains every Gram-positive colony purple','It contains no nutrients for Gram-negative cells','It converts lactose directly to acid'],'It inhibits most Gram-negative bacteria by interfering with DNA synthesis','PEA is selective for many Gram-positive organisms.'),
    mcq('L34-H-014','hard',4,'EMB and MAC media','LM04 Note lines 552-553','EMB and MacConkey media are both selective and differential because they do what?',['Favor Gram-negative growth and distinguish sugar fermentation','Favor Gram-positive growth and detect endospores','Grow only fungi and detect capsules','Prevent all growth except viruses'],'Favor Gram-negative growth and distinguish sugar fermentation','They select for Gram-negative organisms and distinguish them by fermentation, such as lactose use.'),
    mcq('L34-H-015','hard',4,'Mannitol salt agar','LM04 Note line 555','A colony grows on MSA and turns the medium yellow. What does this indicate?',['Salt tolerance and mannitol fermentation with acid production','Acid-fast cell walls and capsule production','No growth and no fermentation','Gram-negative selection only'],'Salt tolerance and mannitol fermentation with acid production','MSA selects for organisms tolerating 7.5% NaCl; acid from mannitol fermentation turns phenol red yellow.'),
    mcq('L34-H-016','hard',4,'Blood agar','LM04 Note line 557','Why is blood agar both enriched and differential?',['Blood supplies extra nutrients and hemolysis distinguishes organisms','It contains only inorganic salts and has no indicator','It inhibits all fastidious bacteria','It separates cells solely by motility'],'Blood supplies extra nutrients and hemolysis distinguishes organisms','Blood supports demanding organisms and reveals hemolysin activity.'),
    mcq('L34-H-017','hard',4,'Streak isolation','LM04 Note lines 717-725','What is the core principle of streak isolation?',['Progressively dilute cells across the agar until isolated CFUs form colonies','Increase cell density in every section','Keep the same unsterilized loop throughout','Mix agar and broth into one medium'],'Progressively dilute cells across the agar until isolated CFUs form colonies','Successive sterile streaks separate individual colony-forming units.'),
    mcq('L34-H-018','hard',4,'Streak-plate error','LM04 PDF pp.2-4','What is the most likely result if the loop is not sterilized between streak sectors?',['Poor dilution and confluent growth with few isolated colonies','No growth in the first sector','Perfect isolation in every sector','Only fungi will grow'],'Poor dilution and confluent growth with few isolated colonies','Carrying the full cell load forward prevents the progressive dilution needed for isolation.'),
    short('L34-H-019','hard',4,'Culture formats','LM04 Note line 542 · Instructor review slide 16','Which culture format in the figure provides the largest solid surface for separating a mixed culture?',['agar plate','plate','petri plate','agar petri dish'],'Agar plate','Agar plates provide a broad surface where streak dilution can produce isolated colonies.',media),
    short('L34-H-020','hard',4,'Pure culture isolation','LM04 Note lines 708-725 · Instructor review slide 18','Name the technique illustrated for progressively diluting a mixed inoculum across an agar surface.',['streak plate','streak plating','streak isolation','t streak','t-streak'],'Streak-plate isolation','Streaking successively dilutes cells until separate colony-forming units can grow.',streak)
  ];
})();
